config setup
    charondebug="all"
    uniqueids=no

conn hybrid-cloud
    left=10.0.0.10
    leftsubnet=10.0.0.0/24
    right=10.0.0.1
    rightsubnet=172.16.1.0/24
    authby=secret
    keyexchange=ikev1
    aggressive=no
    ike=aes256-sha1-modp1024
    esp=aes256-sha1
    type=tunnel
    auto=start
    forceencaps=yes
